apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-allhosts-serviceentry
  namespace: {{ .Release.Name }}
spec:
  hosts:
    - "*.{{ .Release.Name }}.svc.cluster.local"
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
    - number: 3000
      host: salonservice-api-service
      name: tcp-salonservice-api-service
      protocol: TCP
    - number: 5432
      host: salonservice-db-service
      name: tcp-salonservice-db-service
      protocol: TCP
#    - number: 80
#     name: http
#     protocol: HTTP
#    - number: 443
#      name: https
#      protocol: HTTPS
#    - number: 3000
#      name: http-salonservice-api-service
#      protocol: HTTP
#    - number: 5432
#      name: tcp-salonservice-db-service
#      protocol: TCP
