apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    app: auth-service
  ports:
    - name: {{ .Values.authService.service.name }}
      port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.ports.containerPort }}