apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: server
          image: {{ printf "%s:%s" .Values.authService.image.repository .Values.authService.image.tag }}
          ports:
            - containerPort: {{ .Values.authService.ports.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.authService.resources.requests.cpu }}
              memory: {{ .Values.authService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.authService.resources.limits.cpu }}
              memory: {{ .Values.authService.resources.limits.memory }}