apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: authservice
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: api
          image: {{ printf "%s:%s" .Values.authService.image.repository .Values.authService.image.tag }}
          imagePullPolicy: {{ .Values.authService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.authService.ports.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.authService.resources.requests.cpu }}
              memory: {{ .Values.authService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.authService.resources.limits.cpu }}
              memory: {{ .Values.authService.resources.limits.memory }}