#What Docker Image we are using and what is the Name of the Application
#Furthermore you will define how many PODS you wanna have
# kubectl apply -f .\backend-deployment.yaml -- Create the Workloads (Node with 3 Pods) Cluster must be available!
apiVersion: apps/v1
kind: Deployment
metadata:
  #Workloads
  name: salon-backend
spec:
  selector:
    matchLabels:
      run: salon-backend
  replicas: 1
  template:
    metadata:
      labels:
        run: salon-backend
    spec:
      containers:
        - name: salon-backend-container
          image: gcr.io/spitzkick/salon-backend:v1.2 #gcr.io/pat-kub/salon-backend:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              value: postgresadmin
            - name: POSTGRES_PASSWORD
              value: admin123
            - name: POSTGRES_HOST
              value: postgres
