apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: busybox
    stage: production
    owner: spitzkick
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
      stage: production
      owner: spitzkick
  template:
    metadata:
      labels:
        app: busybox
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: busybox
          image: gcr.io/spitzkick/busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
