apiVersion: v1
kind: Service
metadata:
  name: debian-test
  namespace: {{ .Release.Name }}
  labels:
    app: debian-test
    stage: production
    owner: spitzkick
spec:
  type: {{ .Values.salonServiceDb.service.type }}
  ports:
    - name: {{ .Values.salonServiceDb.service.name }}
      port: {{ .Values.salonServiceDb.service.port }}
      targetPort: {{ .Values.salonServiceDb.ports.containerPort }}
  selector:
    app: debian-test
    stage: production
    owner: spitzkick
