apiVersion: v1
kind: Pod
metadata:
name: busybox
  namespace: {{ .Release.Name }}
spec:
  containers:
    image: busybox
    command:
      sleep
      "3600"
    imagePullPolicy: Always
    name: busybox
    restartPolicy: Always
