##################################################################################################
# Productpage services test
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: spitzkickpage
  namespace: {{ .Release.Name }}
  labels:
    app: sptizkickpage
    service: sptizkickpage
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.frontend.service.type }}
  selector:
    app: spitzkickpage
    stage: production
    owner: spitzkick



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spitzkickpage-v1
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spitzkickpage
      stage: production
      owner: spitzkick
  template:
    metadata:
      labels:
        app: spitzkickpage
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: spitzkickpage
          image: {{ printf "%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
