apiVersion: v1
kind: Service
metadata:
  name: spitzkickpage
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickpage
    service: spitzkickpage
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: {{ .Values.frontend.service.name }}
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.ports.containerPort }}
  selector:
    app: spitzkickpage
    stage: production
    owner: spitzkick
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{ .Release.Name }}
data:
  config.json: |-
    {
      "apiUrl": {{ printf "%s" .Release.Name  }},
      "apiPort": "80",
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spitzkickpage-v1
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickpage
    version: v1
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: spitzkickpage
      stage: production
      owner: spitzkick
  template:
    metadata:
      labels:
        app: spitzkickpage
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: spitzkickpage
          image: {{ printf "%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.ports.containerPort }}
          env:
            - name: AUTH_SERVICE_ADDR
              value: {{ printf "%s.%s%s" .Release.Name .Values.global.domain .Values.env.salonService.apiEntryPoint }}
            - name: SALON_SERVICE_ADDR
              value: {{ printf "%s.%s%s" .Release.Name .Values.global.domain .Values.global.domain .Values.env.authService.apiEntryPoint }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: {{ .Release.Name }}-frontend-volume
                mountPath: /usr/share/nginx/html/assets/
      volumes:
        - name: tmp
          emptyDir: {}
        - name: {{ .Release.Name }}-frontend-volume
            configMap:
              name: {{ .Release.Name }}-frontend-config
