##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: spitzkickpage
  namespace: {{ .Release.Name }}
  labels:
    app: sptizkickpage
    service: sptizkickpage
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: spitzkickpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spitzkickpage-v1
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spitzkickpage
      version: v1
  template:
    metadata:
      labels:
        app: spitzkickpage
        version: v1
    spec:
      containers:
        - name: spitzkickpage
          image: gcr.io/spitzkick/master-salon-frontend-minimal
          tag: latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
