##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: sptizkickpage
  namespace: {{ .Release.Name }}
  labels:
    app: sptizkickpage
    service: sptizkickpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: sptizkickpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sptizkickpage-v1
  labels:
    app: sptizkickpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sptizkickpage
      version: v1
  template:
    metadata:
      labels:
        app: sptizkickpage
        version: v1
    spec:
      containers:
        - name: sptizkickpage
          image: gcr.io/spitzkick/master-salon-frontend-minimal
          tag: latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
