apiVersion: v1
kind: Service
metadata:
  name: salonservice-db-service
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-service
    stage: production
    owner: spitzkick
spec:
  type: {{ .Values.salonServiceDb.service.type }}
  ports:
    - name: {{ .Values.salonServiceDb.service.name }}
      port: {{ .Values.salonServiceDb.service.port }}
      targetPort: {{ .Values.salonServiceDb.ports.containerPort }}
  selector:
    app: salonservice-db-instance
    stage: production
    owner: spitzkick
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: salonservice-db-config
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-config
    stage: production
    owner: spitzkick
data:
  POSTGRESQL_DATABASE: {{ .Values.env.salonServiceDb.dbName }}
  POSTGRESQL_USERNAME: {{ .Values.env.salonServiceDb.dbUser }}
  POSTGRESQL_PASSWORD: {{ .Values.env.salonServiceDb.dbPassword }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salonservice-db-pv-claim
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-pv-claim
    stage: production
    owner: spitzkick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salonservice-db
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: salonservice-db-instance
      stage: production
      owner: spitzkick
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        app: salonservice-db-instance
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: salonservice-db-instance-container
          image: {{ printf "%s:%s" .Values.salonServiceDb.image.repository .Values.salonServiceDb.image.tag }}
          imagePullPolicy: {{ .Values.salonServiceDb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.salonServiceDb.ports.containerPort }}
          envFrom:
            - configMapRef:
                name: salonservice-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: salonservice-db-pv
              subPath: postgres
      volumes:
        - name: salonservice-db-pv
          persistentVolumeClaim:
            claimName: salonservice-db-pv-claim
