#Storing all the related information for the PostgreSQL
#These information will be used by the PostgreSQL Pod in the
#deployment template

#kubectl create -f salonservice-db-configmap.yaml
#kubectl delete configmap postgres-config

apiVersion: v1
kind: ConfigMap
metadata:
  name: salonservice-db-config
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-config
    stage: production
    owner: spitzkick
data:
  POSTGRES_DB: {{ .Values.env.salonServiceDb.dbName }}
  POSTGRES_USER: {{ .Values.env.salonServiceDb.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.env.salonServiceDb.dbPassword }}
