#minikube service backend
apiVersion: v1
kind: Service
metadata:
  name: salonservice-api-service
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-api-service
    stage: production
    owner: spitzkick
spec:
  type: {{ .Values.salonService.service.type }}
  selector:
    app: salonservice-api-instance
    stage: production
    owner: spitzkick
  ports:
    - name: {{ .Values.salonService.service.name }}
      port: {{ .Values.salonService.service.port }}
      targetPort: {{ .Values.salonService.ports.containerPort }}
