apiVersion: v1
kind: Service
metadata:
  name: salonservice-api-service
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-api-service
    stage: production
    owner: spitzkick
spec:
  type: {{ .Values.salonService.service.type }}
  ports:
    - name: {{ .Values.salonService.service.name }}
      port: {{ .Values.salonService.service.port }}
      targetPort: {{ .Values.salonService.ports.containerPort }}
  selector:
    app: salonservice-api-instance
    stage: production
    owner: spitzkick
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #Name of the Workloads
  name: salonservice-api
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-api
    stage: production
    owner: spitzkick
spec:
  selector:
    matchLabels:
      #Get all Pods based on that label
      app: salonservice-api-instance
      stage: production
      owner: spitzkick
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        #Labels of the single pod
        app: salonservice-api-instance
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: salonservice-api-instance-container #Container name which is running in the Pod
          image: {{ printf "%s:%s" .Values.salonService.image.repository .Values.salonService.image.tag }}
          imagePullPolicy: {{ .Values.salonService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.salonService.ports.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.salonServiceDb.dbHost }}
            - name: DB_DATABASE
              value: {{ .Values.env.salonServiceDb.dbName }}
            - name: DB_USERNAME
              value: {{ .Values.env.salonServiceDb.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.env.salonServiceDb.dbPassword }}
