kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
