#kubectl logs postgres-697b5bcf8b-2w6dv -p
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salonservice-db
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: salonservice-db-instance
      stage: production
      owner: spitzkick
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        app: salonservice-db-instance
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: salonservice-db
          image: {{ printf "%s:%s" .Values.salonServiceDb.image.repository .Values.salonServiceDb.image.tag }}
          imagePullPolicy: {{ .Values.salonServiceDb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.salonServiceDb.ports.containerPort }}
          envFrom:
            - configMapRef:
                name: salonservice-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: salonservice-db-pv
              subPath: postgres
      volumes:
        - name: salonservice-db-pv
          persistentVolumeClaim:
            claimName: salonservice-db-pv-claim
