#minikube service postgres-service-salon
apiVersion: v1
kind: Service
metadata:
  name: salonservice-db-service
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-service
    stage: production
    owner: spitzkick
spec:
  type: {{ .Values.salonServiceDb.service.type }}
  ports:
    - name: {{ .Values.salonServiceDb.service.name }}
      port: {{ .Values.salonServiceDb.service.port }}
      targetPort: {{ .Values.salonServiceDb.ports.containerPort }}
      protocol: TCP
  selector:
    app: salonservice-db-instance
    stage: production
    owner: spitzkick
