kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: salonservice-db-pv-claim
  namespace: {{ .Release.Name }}
  labels:
    app: salonservice-db-pv-claim
    stage: production
    owner: spitzkick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
