#kubectl get vs
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - "www.speedl.de"
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            regex: /{{ .Release.Name }}/app
            ignoreUriCase: true
            rewrite: /
      route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
    - match:
        - uri:
            regex: /{{ .Release.Name }}/api
            ignoreUriCase: true
            rewrite: /
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
