apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "%s.%s" .Release.Name .Values.global.domain }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: {{ .Values.env.salonService.apiEntryPoint2 }}
        route:
          - destination:
              host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
    - match:
        - uri:
            prefix: {{ .Values.env.salonService.apiEntryPoint }}
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
    - match:
        - uri:
            prefix: {{ .Values.env.appointmentService.apiEntryPoint }}
      route:
        - destination:
            host: {{ printf "appointment-api-service.%s.svc.cluster.local" .Release.Name }}
    - route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}

