#kubectl get vs <vs-named>
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "%s.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: "/salon"
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
    - route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}

