#kubectl get vs
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "www.speedl.de%s" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
