#kubectl get vs <vs-name>
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - spitzkick-gateway
  http:
    - match:
       - uri:
           prefix: "/app/"
         rewrite:
           uri: "/"
      route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
            port:
              number: 80
    - match:
        - uri:
            prefix: "/api"
          rewrite:
            uri: " "
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
