#kubectl get vs <vs-name>
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - "speedl.de"
  gateways:
    - spitzkick-gateway
  http:
    - route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /{{ .Release.Name }}/api
            ignoreUriCase: true
            rewrite:
              uri: /api
      route:
        - destination:
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
