#kubectl get vs
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "www.speedl.de/%s" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
            port:
              number: 80
