#kubectl get vs <vs-name>
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-SpitzkickEntryPoint-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "%s.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
    - uri:
        prefix: "/"
      delegate:
      name: {{ .Release.Name }}-frontend-ingress
      namespace: default
    - match:
        - uri:
            prefix: "/api"
      delegate:
        name: {{ .Release.Name }}-api-ingress
        namespace: default
