#kubectl get vs
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "*.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: /{{ printf "%s/api" .Release.Name }}
        route:
          - destination:
              port:
                number: 80
              host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
