#kubectl get vs
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - "*.speedl.de"
  gateways:
    - spitzkick-gateway
  http:
    - match:
          - uri:
              prefix: /{{ printf "%s/app" .Release.Name }}
      route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /{{ printf "%s/app" .Release.Name }}
        route:
          - destination:
              host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
              port:
                number: 80

