#kubectl get vs
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "%s.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
          - uri:
              prefix: /api
      route:
        - destination:
            host: {{ printf "spitzkickpage.%s.svc.cluster.local" .Release.Name }}
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: salonservice-api-ingress
spec:
  hosts:
    - {{ printf "%s.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 80
            host: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
          weight: 100
