#kubectl get vs <vs-name>
#- {{ printf ".speedl.de" .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "%s.speedl.de" .Release.Name }}
  gateways:
    - spitzkick-gateway
  http:
  - name: "salonservice-api"
    match:
    - uri:
        exact: "/salons/api"
    redirect:
        uri: "/api"
        authority: {{ printf "salonservice-api-service.%s.svc.cluster.local" .Release.Name }}
