apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    app: authservice
  ports:
    - name: {{ .Values.authService.service.name }}
      port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.ports.containerPort }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pv-claim
  namespace: {{ .Release.Name }}
  labels:
    app: auth-pv-claim
    stage: production
    owner: spitzkick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: authservice
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: api
          image: {{ printf "%s:%s" .Values.authService.image.repository .Values.authService.image.tag }}
          imagePullPolicy: {{ .Values.authService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.authService.ports.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.authService.resources.requests.cpu }}
              memory: {{ .Values.authService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.authService.resources.limits.cpu }}
              memory: {{ .Values.authService.resources.limits.memory }}
          volumeMounts:
            - mountPath: /usr/src/app/dist/gitrepo
              name: auth-pv
      volumes:
        - name: auth-pv
          persistentVolumeClaim:
            claimName: auth-pv-claim