apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    k8s-app: prometheus
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: prometheus
    k8s-app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
