apiVersion: v1
kind: Service
metadata:
  name: spitzkickhome
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickhome
    service: spitzkickhome
spec:
  type: {{ .Values.spitzkick-home.service.type }}
  ports:
    - name: {{ .Values.spitzkick-home.service.name }}
      port: {{ .Values.spitzkick-home.service.port }}
      targetPort: {{ .Values.spitzkick-home.ports.containerPort }}
  selector:
    app: spitzkickhome
    stage: production
    owner: spitzkick
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spitzkickhome
  namespace: {{ .Release.Name }}
  labels:
    app: spitzkickhome
    version: v1
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: spitzkickhome
      stage: production
      owner: spitzkick
  template:
    metadata:
      labels:
        app: spitzkickhome
        stage: production
        owner: spitzkick
    spec:
      containers:
        - name: spitzkickhome
          image: {{ printf "%s:%s" .Values.spitzkick-home.image.repository .Values.spitzkick-home.image.tag }}
          imagePullPolicy: {{ .Values.spitzkick-home.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.spitzkick-home.ports.containerPort }}
