apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "www.%s" .Values.global.domain }}
  gateways:
    - spitzkick-gateway
  http:
    - match:
        - uri:
            prefix: {{ .Values.env.authService.apiEntryPoint }}
      route:
        - destination:
            host: {{ printf "authservice.%s.svc.cluster.local" .Release.Name }}
    - route:
        - destination:
            host: {{ printf "spitzkickhome.%s.svc.cluster.local" .Release.Name }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-Grafana-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "grafana.%s" .Values.global.domain }}
  gateways:
    - spitzkick-gateway
  http:
    - route:
        - destination:
            host: {{ printf "prometheus-grafana.%s.svc.cluster.local" .Release.Name }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-Prometheus-vs-ingress
  namespace: default
spec:
  hosts:
    - {{ printf "prometheus.%s" .Values.global.domain }}
  gateways:
    - spitzkick-gateway
  http:
    - route:
        - destination:
            host: {{ printf "prometheus-prometheus.%s.svc.cluster.local" .Release.Name }}


