env:
  frontendService:
    addr: frontendService
    port: 9080
  authService:
    addr: authservice
    apiEntryPoint: /auth
    port: 8080
  salonService:
    addr: salonservice
    apiEntryPoint: /salon
    port: 3000
  salonServiceDb:
    addr: salonservice-db
    port: 5432
    dbHost: salonservice-db-service
    dbName: salon
    dbUser: postgresadmin
    dbPassword: admin123

global:
  replicas: 1
  domain: speedl.de

authService:
  image:
    repository: gcr.io/spitzkick/master-auth-service
    tag: latest
    pullPolicy: Always
  ports:
    containerPort: 8080

  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
  service:
    type: ClusterIP
    name: TCP
    port: 8080

salonService:
  image:
    repository: gcr.io/spitzkick/master-salon
    tag: latest
    pullPolicy: Always
  ports:
    containerPort: 3000

  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
  service:
    type: ClusterIP
    name: TCP
    port: 3000

salonServiceDb:
  image:
    repository: bitnami/postgresql
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    containerPort: 5432

  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
  service:
    type: ClusterIP
    name: TCP
    port: 5432

frontend:
  image:
    repository: gcr.io/spitzkick/master-salon-frontend-minimal
    tag: latest
    pullPolicy: Always
  ports:
    containerPort: 80
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    name: TCP
    port: 80
